java_test(
  name = "LibraryTest",
  srcs = ["LibraryTest.java"],
  size = "small",
  deps = [
    "@com_google_guava//jar",
    "@com_google_guava_testlib//jar",
    "@com_google_truth//jar",
    "@junit//jar",
    "//java/com/example/tests:lib",
  ],
)
